lang: ruby
before_install: gem install bundler --pre
install:
  - gem update --system
  - bundle update
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.4
  - 2.3.0
  - rbx-2
  - jruby-head
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: rbx-2
    - env: SINATRA_EDGE=true
    - rvm: ruby-head
    - rvm: jruby-head
